# -*- coding: utf-8 -*-
"""gutenberg_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Twz_Xlr8r3bC6KtpIUTRG39ktbomeRg5
"""

import re
import requests
import csv
from collections import Counter



def download_gutenberg_text(url: str) -> str:
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    return response.text

def strip_gutenberg_boilerplate(text: str) -> str:
    start_pattern = r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK .* \*\*\*"
    end_pattern = r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK .* \*\*\*"

    start_match = re.search(start_pattern, text, re.IGNORECASE)
    end_match = re.search(end_pattern, text, re.IGNORECASE)

    if start_match:
        text = text[start_match.end():]
    if end_match:
        text = text[:end_match.start()]

    return text

def clean_words(text: str) -> list[str]:
    text = text.lower()
    text = text.replace("’", "'").replace("‘", "'")
    text = re.sub(r"[^a-z0-9'\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text.split()

def write_bigrams(words: list[str], output_csv: str) -> None:
    with open(output_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["current_word", "next_word"])
        for i in range(len(words) - 1):
            writer.writerow([words[i], words[i + 1]])

def build_unigram_frequencies(words):
    return Counter(words)

def save_unigrams(freq, filename):
    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["word", "frequency"])

        for word, count in freq.most_common():
            writer.writerow([word, count])

def main():
    url = "https://www.gutenberg.org/files/84/84-0.txt"  # Frankenstein
    raw = download_gutenberg_text(url)
    stripped = strip_gutenberg_boilerplate(raw)
    words = clean_words(stripped)
    write_bigrams(words, "bigrams.csv")
    print("Saved bigrams.csv")

if __name__ == "__main__":
    main()